version: '3.8'
services:
  dev:
    build:
      context: ./
      target: development
    volumes:
      - .:/src
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
  prod:
    build:
      context: ./
      target: production
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production