services:
  dev:
    build:
      context: ./
      target: development
    volumes:
      - .:/work
      - /work/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  prod:
    build:
      context: ./
      target: production
    ports:
      - "3000:3000"
